# Generated by Django 3.1.1 on 2020-09-19 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 15, 53, 38, 646564, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='tags',
            field=models.ManyToManyField(null=True, to='tasks.Tag'),
        ),
    ]
