# Generated by Django 3.1.1 on 2020-09-28 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200920_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 9, 25, 20, 775183, tzinfo=utc)),
        ),
    ]
